#!/bin/bash

if [ $# -ne 2 ]; then
    echo >&2 "Usage: $0 <directory> <file suffix>"
    echo >&2 "     e.g: $0 . gpx"
    exit 1
fi

#shopt -s nullglob
for i in $1/*.$2
do
  if [ 	! -f "$i".in_strava ]; then
    echo "Uploading $i..."
    result=$(/bin/bash "$(dirname $0)/stravaup" $i )
    if echo "${result}" | grep -q 'Your activity is still being processed.'; then
      echo "Upload OK. Response: " 
      echo "${result}"
      echo "${result}" > "$i".in_strava
    else
      (>&2 echo -e "\e[01;31m Unrecognized response (considered upload FAIL): " ; echo "${result}";echo -e "\e[0m")
    fi
  fi
done
